name: Run unit tests
on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install -g pnpm

      - name: Run tests
        env:
          SWAGGER_URL: ${{ secrets.SWAGGER_URL_DEV }}
        run: |
          pnpm
          pnpm test:ci
